name: Release

on:
  push:
    branches: 
      - main
      - next
      - next-major
      - alpha
      - beta
      - "*.x"
  pull_request:
    branches: 
      - main
      - next
      - next-major
      - alpha
      - beta
      - "*.x"

jobs:
  release:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npx semantic-release

      # - run: nom run build --if-present
      # - run: npm test -- --watch=false --browsers=ChromeHeadless
